# Generated by Django 5.0.4 on 2024-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_api', '0002_codemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemodel',
            name='c_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
